# The `needs triage` label is added to new issues
needs-triage:
  issues:
    types: [opened]
    if: "${{ issue-author != 'monacodelisa' }}"
    add-labels: '👀 needs triage'

    comment: >
      :mag: This issue has been marked as "👀 needs triage". Team, please review and prioritize accordingly.