name: 'Label Actions'

on:
  issues:
    types: [labeled, unlabeled]
  pull_request_target:
    types: [labeled, unlabeled]
  discussion:
    types: [labeled, unlabeled]

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v4.0.1
        with:
          repo-token: ${{ secrets.ACCESS_TOKEN }}
          configuration-path: .github/label-actions.yml


